// Code generated by protoc-gen-go. DO NOT EDIT.
// source: github.com/paralin/go-p2pd/control/control-svc.proto

/*
Package control is a generated protocol buffer package.

It is generated from these files:
	github.com/paralin/go-p2pd/control/control-svc.proto

It has these top-level messages:
	CreateNodeRequest
	CreateNodeResponse
	StartNodeRequest
	StartNodeResponse
	ListenNodeRequest
	ListenNodeResponse
*/
package control

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

// CreateNodeRequest is the argument to CreateNode.
type CreateNodeRequest struct {
	// NodeId is the desired ID for the node.
	NodeId string `protobuf:"bytes,1,opt,name=node_id,json=nodeId" json:"node_id,omitempty"`
}

func (m *CreateNodeRequest) Reset()                    { *m = CreateNodeRequest{} }
func (m *CreateNodeRequest) String() string            { return proto.CompactTextString(m) }
func (*CreateNodeRequest) ProtoMessage()               {}
func (*CreateNodeRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *CreateNodeRequest) GetNodeId() string {
	if m != nil {
		return m.NodeId
	}
	return ""
}

// CreateNodeResponse is the response to CreateNode.
type CreateNodeResponse struct {
	// NodePeerId is the peer ID of the new node.
	NodePeerId string `protobuf:"bytes,1,opt,name=node_peer_id,json=nodePeerId" json:"node_peer_id,omitempty"`
}

func (m *CreateNodeResponse) Reset()                    { *m = CreateNodeResponse{} }
func (m *CreateNodeResponse) String() string            { return proto.CompactTextString(m) }
func (*CreateNodeResponse) ProtoMessage()               {}
func (*CreateNodeResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *CreateNodeResponse) GetNodePeerId() string {
	if m != nil {
		return m.NodePeerId
	}
	return ""
}

// StartNodeRequest is the argument to the StartNode call.
type StartNodeRequest struct {
	// NodeId is the ID of the node as given at creation time.
	NodeId string `protobuf:"bytes,1,opt,name=node_id,json=nodeId" json:"node_id,omitempty"`
}

func (m *StartNodeRequest) Reset()                    { *m = StartNodeRequest{} }
func (m *StartNodeRequest) String() string            { return proto.CompactTextString(m) }
func (*StartNodeRequest) ProtoMessage()               {}
func (*StartNodeRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

func (m *StartNodeRequest) GetNodeId() string {
	if m != nil {
		return m.NodeId
	}
	return ""
}

// StartNodeResponse is the response to the StartNode call.
type StartNodeResponse struct {
	// NodePeerId is the peer ID of the node.
	NodePeerId string `protobuf:"bytes,1,opt,name=node_peer_id,json=nodePeerId" json:"node_peer_id,omitempty"`
	// NodeListenAddrs are the addresses the node is listening on.
	NodeListenAddrs []string `protobuf:"bytes,2,rep,name=node_listen_addrs,json=nodeListenAddrs" json:"node_listen_addrs,omitempty"`
}

func (m *StartNodeResponse) Reset()                    { *m = StartNodeResponse{} }
func (m *StartNodeResponse) String() string            { return proto.CompactTextString(m) }
func (*StartNodeResponse) ProtoMessage()               {}
func (*StartNodeResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{3} }

func (m *StartNodeResponse) GetNodePeerId() string {
	if m != nil {
		return m.NodePeerId
	}
	return ""
}

func (m *StartNodeResponse) GetNodeListenAddrs() []string {
	if m != nil {
		return m.NodeListenAddrs
	}
	return nil
}

// ListenNodeRequest is the argument to the ListenNode call.
type ListenNodeRequest struct {
	// NodeId is the ID of the node as given at creation time.
	NodeId string `protobuf:"bytes,1,opt,name=node_id,json=nodeId" json:"node_id,omitempty"`
	// Addr is the address to listen to.
	Addr string `protobuf:"bytes,2,opt,name=addr" json:"addr,omitempty"`
}

func (m *ListenNodeRequest) Reset()                    { *m = ListenNodeRequest{} }
func (m *ListenNodeRequest) String() string            { return proto.CompactTextString(m) }
func (*ListenNodeRequest) ProtoMessage()               {}
func (*ListenNodeRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{4} }

func (m *ListenNodeRequest) GetNodeId() string {
	if m != nil {
		return m.NodeId
	}
	return ""
}

func (m *ListenNodeRequest) GetAddr() string {
	if m != nil {
		return m.Addr
	}
	return ""
}

// ListenNodeResponse is the response to the ListenNode call.
type ListenNodeResponse struct {
	// NodePeerId is the peer ID of the node.
	NodePeerId string `protobuf:"bytes,1,opt,name=node_peer_id,json=nodePeerId" json:"node_peer_id,omitempty"`
	// NodeListenAddrs are the addresses the node is listening on.
	NodeListenAddrs []string `protobuf:"bytes,2,rep,name=node_listen_addrs,json=nodeListenAddrs" json:"node_listen_addrs,omitempty"`
}

func (m *ListenNodeResponse) Reset()                    { *m = ListenNodeResponse{} }
func (m *ListenNodeResponse) String() string            { return proto.CompactTextString(m) }
func (*ListenNodeResponse) ProtoMessage()               {}
func (*ListenNodeResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{5} }

func (m *ListenNodeResponse) GetNodePeerId() string {
	if m != nil {
		return m.NodePeerId
	}
	return ""
}

func (m *ListenNodeResponse) GetNodeListenAddrs() []string {
	if m != nil {
		return m.NodeListenAddrs
	}
	return nil
}

func init() {
	proto.RegisterType((*CreateNodeRequest)(nil), "control.CreateNodeRequest")
	proto.RegisterType((*CreateNodeResponse)(nil), "control.CreateNodeResponse")
	proto.RegisterType((*StartNodeRequest)(nil), "control.StartNodeRequest")
	proto.RegisterType((*StartNodeResponse)(nil), "control.StartNodeResponse")
	proto.RegisterType((*ListenNodeRequest)(nil), "control.ListenNodeRequest")
	proto.RegisterType((*ListenNodeResponse)(nil), "control.ListenNodeResponse")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// Client API for ControlService service

type ControlServiceClient interface {
	// CreateNode creates a new node.
	CreateNode(ctx context.Context, in *CreateNodeRequest, opts ...grpc.CallOption) (*CreateNodeResponse, error)
	// StartNode starts a node.
	StartNode(ctx context.Context, in *StartNodeRequest, opts ...grpc.CallOption) (*StartNodeResponse, error)
	// ListenNode instructs a node to listen to an address.
	ListenNode(ctx context.Context, in *ListenNodeRequest, opts ...grpc.CallOption) (*ListenNodeResponse, error)
}

type controlServiceClient struct {
	cc *grpc.ClientConn
}

func NewControlServiceClient(cc *grpc.ClientConn) ControlServiceClient {
	return &controlServiceClient{cc}
}

func (c *controlServiceClient) CreateNode(ctx context.Context, in *CreateNodeRequest, opts ...grpc.CallOption) (*CreateNodeResponse, error) {
	out := new(CreateNodeResponse)
	err := grpc.Invoke(ctx, "/control.ControlService/CreateNode", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *controlServiceClient) StartNode(ctx context.Context, in *StartNodeRequest, opts ...grpc.CallOption) (*StartNodeResponse, error) {
	out := new(StartNodeResponse)
	err := grpc.Invoke(ctx, "/control.ControlService/StartNode", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *controlServiceClient) ListenNode(ctx context.Context, in *ListenNodeRequest, opts ...grpc.CallOption) (*ListenNodeResponse, error) {
	out := new(ListenNodeResponse)
	err := grpc.Invoke(ctx, "/control.ControlService/ListenNode", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for ControlService service

type ControlServiceServer interface {
	// CreateNode creates a new node.
	CreateNode(context.Context, *CreateNodeRequest) (*CreateNodeResponse, error)
	// StartNode starts a node.
	StartNode(context.Context, *StartNodeRequest) (*StartNodeResponse, error)
	// ListenNode instructs a node to listen to an address.
	ListenNode(context.Context, *ListenNodeRequest) (*ListenNodeResponse, error)
}

func RegisterControlServiceServer(s *grpc.Server, srv ControlServiceServer) {
	s.RegisterService(&_ControlService_serviceDesc, srv)
}

func _ControlService_CreateNode_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateNodeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ControlServiceServer).CreateNode(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/control.ControlService/CreateNode",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ControlServiceServer).CreateNode(ctx, req.(*CreateNodeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ControlService_StartNode_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(StartNodeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ControlServiceServer).StartNode(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/control.ControlService/StartNode",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ControlServiceServer).StartNode(ctx, req.(*StartNodeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ControlService_ListenNode_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListenNodeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ControlServiceServer).ListenNode(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/control.ControlService/ListenNode",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ControlServiceServer).ListenNode(ctx, req.(*ListenNodeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _ControlService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "control.ControlService",
	HandlerType: (*ControlServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateNode",
			Handler:    _ControlService_CreateNode_Handler,
		},
		{
			MethodName: "StartNode",
			Handler:    _ControlService_StartNode_Handler,
		},
		{
			MethodName: "ListenNode",
			Handler:    _ControlService_ListenNode_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "github.com/paralin/go-p2pd/control/control-svc.proto",
}

func init() {
	proto.RegisterFile("github.com/paralin/go-p2pd/control/control-svc.proto", fileDescriptor0)
}

var fileDescriptor0 = []byte{
	// 305 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xb4, 0x52, 0x41, 0x4b, 0xf3, 0x40,
	0x10, 0x6d, 0xfb, 0x7d, 0xb4, 0x74, 0x10, 0x35, 0x73, 0xb1, 0xc6, 0x4b, 0xd9, 0x53, 0x51, 0x9b,
	0x42, 0x15, 0xcf, 0x4a, 0x85, 0x52, 0x10, 0x91, 0xf4, 0x07, 0x94, 0x4d, 0x76, 0xa8, 0x81, 0x98,
	0x5d, 0x77, 0xb7, 0xfd, 0xcd, 0xfe, 0x0c, 0xc9, 0xa6, 0x26, 0xc1, 0xf4, 0x90, 0x8b, 0xa7, 0xdd,
	0x79, 0xf3, 0x76, 0xe6, 0xf1, 0xde, 0xc2, 0xfd, 0x36, 0xb1, 0xef, 0xbb, 0x28, 0x88, 0xe5, 0xc7,
	0x4c, 0x71, 0xcd, 0xd3, 0x24, 0x9b, 0x6d, 0xe5, 0x54, 0xcd, 0x95, 0x98, 0xc5, 0x32, 0xb3, 0x5a,
	0xa6, 0x3f, 0xe7, 0xd4, 0xec, 0xe3, 0x40, 0x69, 0x69, 0x25, 0x0e, 0x0e, 0x10, 0xbb, 0x05, 0x6f,
	0xa1, 0x89, 0x5b, 0x7a, 0x95, 0x82, 0x42, 0xfa, 0xdc, 0x91, 0xb1, 0x78, 0x01, 0x83, 0x4c, 0x0a,
	0xda, 0x24, 0x62, 0xd4, 0x1d, 0x77, 0x27, 0xc3, 0xb0, 0x9f, 0x97, 0x2b, 0xc1, 0x1e, 0x00, 0xeb,
	0x6c, 0xa3, 0x64, 0x66, 0x08, 0xc7, 0x70, 0xe2, 0xe8, 0x8a, 0x48, 0x57, 0x6f, 0x20, 0xc7, 0xde,
	0x88, 0xf4, 0x4a, 0xb0, 0x1b, 0x38, 0x5f, 0x5b, 0xae, 0x6d, 0xab, 0x25, 0x1c, 0xbc, 0x1a, 0xb9,
	0xed, 0x0e, 0xbc, 0x06, 0xcf, 0x31, 0xd2, 0xc4, 0x58, 0xca, 0x36, 0x5c, 0x08, 0x6d, 0x46, 0xbd,
	0xf1, 0xbf, 0xc9, 0x30, 0x3c, 0xcb, 0x1b, 0x2f, 0x0e, 0x7f, 0xca, 0x61, 0xf6, 0x08, 0x5e, 0x51,
	0xb6, 0x11, 0x84, 0x08, 0xff, 0xf3, 0x69, 0xa3, 0x9e, 0x43, 0xdd, 0x9d, 0x45, 0x80, 0xf5, 0x09,
	0x7f, 0xa1, 0x72, 0xfe, 0xd5, 0x85, 0xd3, 0x45, 0x91, 0xd3, 0x9a, 0xf4, 0x3e, 0x89, 0x09, 0x97,
	0x00, 0x55, 0x00, 0xe8, 0x07, 0x87, 0x18, 0x83, 0x46, 0x86, 0xfe, 0xd5, 0xd1, 0x5e, 0xa1, 0x93,
	0x75, 0xf0, 0x19, 0x86, 0xa5, 0xc9, 0x78, 0x59, 0x72, 0x7f, 0xa7, 0xe4, 0xfb, 0xc7, 0x5a, 0xe5,
	0x94, 0x25, 0x40, 0xe5, 0x42, 0x4d, 0x4e, 0xc3, 0xdc, 0x9a, 0x9c, 0xa6, 0x6d, 0xac, 0x13, 0xf5,
	0xdd, 0xb7, 0xbc, 0xfb, 0x0e, 0x00, 0x00, 0xff, 0xff, 0xea, 0x8d, 0x48, 0xc1, 0xce, 0x02, 0x00,
	0x00,
}
